apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wg2y33w0n-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wg2y33w0n-java-quarkus-gitops